name-template: "SetSaver v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐞 Bug Fixes"
    labels:
      - "bug"

change-template: "- $TITLE "

template: |
  ## Release Notes – SetSaver $NEXT_PATCH_VERSION ($DATE)

  $CHANGES
