name: Generate Release Notes

on:
  release:
    types:
      - edited

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-notes-automator
        uses: lodovicoazzini/release-notes-automator@main
        with:
          repo: 'lodovicoazzini/set-saver' # The repository where your issues and milestones live
          label_config: |
            [
              {
                "label": "feature",
                "template": "- 🚀 $TITLE",
                "section_title": "Cool New Stuff"
              },
              {
                "label": "bug",
                "template": "- 🐛 $TITLE",
                "section_title": "Oops... Fixed It"
              }
              {
                "label": "maintenance",
                "template": "- 🚧 $TITLE",
                "section_title": "Under the Hood"
              }
            ]
        env:
          ISSUES_REPOSITORY_TOKEN: ${{ secrets.LODOVICOAZZINI_SETSAVER_READ_ISSUES }}
          GH_TOKEN: ${{ secrets.THEREALLLAMA_SETSAVER_WRITE_CONTENT }}