name: Generate Custom Issue Changelog

on:
  release:
    types:
      - published       # When publishing the release (including draft published)
      - prereleased     # Pre-release created or published
      - edited          # When editing the release

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      # Ensure the latest code is checked out (very important!)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional safety check: Skip execution if the release is still a draft (even when 'edited' event fires)
      - name: Check if release is a draft (skip if true)
        if: ${{ github.event.release.draft }}
        run: |
          echo "This is still a draft release. Skipping changelog generation."
          exit 0

      - name: Run custom issue changelog builder
        uses: ./custom-issue-changelog
        with:
          repo: 'lodovicoazzini/set-saver'
          label_config: |
            [
              {
                "label": "feature",
                "template": "- 🚀 $TITLE",
                "section_title": "Features"
              },
              {
                "label": "bug",
                "template": "- 🐛 $TITLE",
                "section_title": "Bug Fixes"
              }
            ]
        env:
          # Token with read access to Repo B (lodovicoazzini/set-saver)
          REPO_B_TOKEN: ${{ secrets.LODOVICOAZZINI_SETSAVER_READ_ISSUES }}
          # Token with write access to Repo A (therealllama/set-saver)
          GITHUB_TOKEN: ${{ secrets.THEREALLLAMA_SETSAVER_WRITE_CONTENT }}