name: Generate Custom Issue Changelog

on:
  release:
    types:
      - published
      - edited
      - prereleased

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-notes-automator from 'main'
        uses: your-org/release-notes-automator@main
        with:
          repo: 'lodovicoazzini/set-saver' # The repository where your issues and milestones live (Repo B)
          label_config: |
            [
              {
                "label": "feature",
                "template": "- 🚀 $TITLE",
                "section_title": "Features"
              },
              {
                "label": "bug",
                "template": "- 🐛 $TITLE",
                "section_title": "Bug Fixes"
              }
            ]
        env:
          ISSUES_REPOSITORY_TOKEN: ${{ secrets.LODOVICOAZZINI_SETSAVER_READ_ISSUES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}