name: Label PRs automatically

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.SET_SAVER_RELEASE_TOKEN }}
